### ISSUE TITLE
detokenize original context

### ISSUE THREAD

**Issue by minstar** [facebookresearch/bio-lm#13]
Hi, I am pleased to use these excellent models!

To detokenize for evaluating word-level (without subword level) tokens,  
is there any efficient way that I can detokenize the subword tokens?

For example, 
```
The Medical Home In dex : -> The Medical Home Index: 
```
In my knowledge, the roberta tokenzier use this special character ```Ġ``` to recognize the subword token, 
but cannot find the character while using this.

**Comment by patrick-s-h-lewis** [comment]
Hey,

I don't think i fully understand your question - you want to map between a list of tokens and a detokenized string?


Patrick

**Comment by minstar** [comment]
Yes, that's correct. 
However, I think I have missed something.
