### ISSUE TITLE
Tokenizer model

### ISSUE THREAD

**Issue by nooralahzadeh** [facebookresearch/bio-lm#6]
Hi, Thanks for sharing the pre-trianed models.
I wonder if there is a possibility to share the tokenizer models?
Thanks

**Comment by patrick-s-h-lewis** [comment]
The tokenizers are available along with the models. 
You should be able to load the tokenizers by downloading a model that uses that tokenizer:

e.g.         
```
tokenizer = RobertaTokenizerFast.from_pretrained(
          model_path,
          add_prefix_space=False
)
```
